### ISSUE TITLE
No HID BRIGHTNESS devices found.

### ISSUE THREAD

**Issue by amanuel2** [ei-grad/usb-hid-brightness#2]
Getting the above result when running usb-hid-brightness, also don't see my monitor when running lsusb so that's probably why. Is there a way to detect my LG Monitor via usb-c which is connected through an HDMI adapter, through specifically [this adapter.](https://www.amazon.com/Club3D-Active-Type-C-Adapter-4K60Hz/dp/B09JSYP8VR/ref=sr_1_1?crid=3RI7HW8KPRRO2&dib=eyJ2IjoiMSJ9.Fb9Jsa52x2TCXZ_sG-PjP_OaFqHbTk82lqMriaOxXuzGjHj071QN20LucGBJIEps.wsff5zvBcQcCLuzAUKtuNwOMYoLrmSGydXn7CZVckqA&dib_tag=se&keywords=Club+3d+CAC+1333&qid=1722803048&sprefix=club+3d+cac+133%2Caps%2C154&sr=8-1)

**Comment by ei-grad** [comment]
> Is there a way to detect my LG Monitor via usb-c which is connected through an HDMI adapter

No. USB interface could only manage monitors which are connected directly via USB Type-C Thunderbolt / USB3.
